services:
  - type: web
    name: aquarevier-editor-backend
    env: docker
    dockerfilePath: editor_backend/Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8000
      - key: GIT_PUSH_TOKEN
        sync: false
      - key: EDITOR_USER
        sync: false
      - key: EDITOR_PASSWORD
        sync: false
