services:
  - type: web
    name: aquarevier-editor-backend
    env: docker
    dockerContext: .
    dockerfilePath: editor_backend/Dockerfile
    envVars:
      - key: EDITOR_USER
        value: florian
      - key: EDITOR_PASSWORD
        generateValue: true
      - key: ENC_PASSWORD
        generateValue: true
      - key: GIT_PUSH_TOKEN
        sync: false
