const { test, expect } = require('@playwright/test');

test.describe('Popup Component Unit Tests', () => {
    test.beforeEach(async ({ page }) => {
        await page.goto('about:blank');

        await page.evaluate(() => {
            window._lastPopupHtml = null;

            // Mock Leaflet strictly and simply
            window.L = {
                marker: () => ({ on: () => {}, getElement: () => document.createElement('div'), bindPopup: (html) => window._lastPopupHtml = html }),
                layerGroup: () => ({ addTo: function() { return this; }, addLayer: function() { return this; } }),
                geoJSON: (data, opts) => {
                    if (data && data.features) {
                        data.features.forEach(f => {
                           if (opts.onEachFeature) {
                               const layer = { bindPopup: (html) => window._lastPopupHtml = html, on: () => {} };
                               opts.onEachFeature(f, layer);
                           }
                        });
                    }
                    return { eachLayer: function() { return this; } };
                },
                divIcon: () => {},
                markerClusterGroup: () => ({ addLayers: function() { return this; }, addLayer: function() { return this; } })
            };
            window.map = { on: () => {} };
            window.overlayMaps = {};
            window.layerDataStore = {};
            window.AQUAREVIER_I18N = null;

            // Strict fetch mock
            window.fetchPromises = [];
            window.fetch = (url) => {
                const p = Promise.resolve({
                    ok: true,
                    json: () => Promise.resolve({
                        features: [{ properties: window._testProperties || {} }]
                    })
                });
                window.fetchPromises.push(p);
                return p;
            };
        });

        const path = require('path');
        const scriptContent = require('fs').readFileSync(path.resolve(__dirname, '../../js/layers-loader.js'), 'utf-8');
        await page.addScriptTag({ content: scriptContent });
    });

    const renderPopupHtml = async (page, p, cfg) => {
        return await page.evaluate(async (args) => {
            window._lastPopupHtml = null;
            window.fetchPromises = [];
            window._testProperties = args.p;

            // Re-evaluate functions passed as strings from cfg if necessary, or just run directly.
            // Since we can't easily pass functions in args.cfg, we will execute any stringified functions back into functions.
            if (args.cfg.popupFields) {
                args.cfg.popupFields.forEach(field => {
                    if (field.exprStr) {
                        field.expr = new Function('return ' + field.exprStr)();
                    }
                });
            }
            if (args.cfg.footerTemplateStr) {
                args.cfg.footerTemplate = new Function('return ' + args.cfg.footerTemplateStr)();
            }

            window.addGeoLayer(args.cfg, window.map, window.overlayMaps, window.layerDataStore);

            // Wait deterministically for the fetch and JSON parsing promises to settle
            await Promise.all(window.fetchPromises);
            await new Promise(r => setTimeout(r, 0)); // yield microtask

            if (window._lastPopupHtml === null) {
                throw new Error("Popup HTML was not generated by L.geoJSON callback.");
            }
            return window._lastPopupHtml;
        }, { p, cfg });
    };

    test('generates basic popup HTML with correct structure', async ({ page }) => {
        const cfg = { id: 'test', file: 'test.geojson', color: '#ff0000', groupLabel: 'Test Group', popupFields: [{ label: '📍', field: 'feld' }] };
        const p = { name: 'Test Name', feld: 'Wert' };

        const popupHtml = await renderPopupHtml(page, p, cfg);

        expect(popupHtml).toContain('<div class="popup-card">');
        expect(popupHtml).toContain('<div class="popup-group" style="color:#ff0000">Test Group</div>');
        expect(popupHtml).toContain('<div class="popup-title">Test Name</div>');
        expect(popupHtml).toContain('<div class="popup-detail">📍 Wert</div>');
    });

    test('sanitizes inputs in popup generation to prevent XSS across properties and config', async ({ page }) => {
        const cfg = {
            id: 'test',
            file: 'test.geojson',
            color: '#ff0000',
            groupLabel: '<script>alert("group")</script>',
            popupFields: [{ label: '<img src=x onerror=a()>', field: 'feld', suffix: ' <svg onload=b()>' }]
        };
        const p = {
            name: '<img src=x onerror=alert(1)>',
            feld: '<script>alert(2)</script>'
        };

        const popupHtml = await renderPopupHtml(page, p, cfg);

        expect(popupHtml).not.toContain('<img');
        expect(popupHtml).not.toContain('<script>');
        expect(popupHtml).toContain('&lt;img src=x onerror=alert(1)&gt;');
        expect(popupHtml).toContain('&lt;script&gt;alert(2)&lt;/script&gt;');
        expect(popupHtml).toContain('&lt;script&gt;alert(&quot;group&quot;)&lt;/script&gt;');
        expect(popupHtml).toContain('&lt;img src=x onerror=a()&gt;');
        expect(popupHtml).toContain('&lt;svg onload=b()&gt;');
    });

    test('uses fallback string for missing names', async ({ page }) => {
        const cfg = { id: 'test', file: 'test.geojson', color: '#ff0000', groupLabel: 'Test', popupFields: [] };
        const p = {};
        const popupHtml = await renderPopupHtml(page, p, cfg);
        expect(popupHtml).toContain('<div class="popup-title">Unbekannt</div>');
    });

    test('evaluates function expressions in popup fields', async ({ page }) => {
        const cfg = {
            id: 'test', file: 'test.geojson', color: '#000', groupLabel: 'Test',
            popupFields: [{ label: 'Expr', exprStr: '(p) => p.val1 + p.val2' }]
        };
        const p = { val1: 'A', val2: 'B' };

        const popupHtml = await renderPopupHtml(page, p, cfg);
        expect(popupHtml).toContain('Expr: AB');
    });

    test('ignores missing values for popup fields', async ({ page }) => {
        const cfg = {
            id: 'test', file: 'test.geojson', color: '#000', groupLabel: 'Test',
            popupFields: [ { label: 'Feld1', field: 'feld1' }, { label: 'Feld2', field: 'feld2' } ]
        };
        const p = { feld1: 'Wert1' };

        const popupHtml = await renderPopupHtml(page, p, cfg);
        expect(popupHtml).toContain('Feld1');
        expect(popupHtml).not.toContain('Feld2');
    });

    test('renders pegel stats and drought trends correctly', async ({ page }) => {
        const cfg = { id: 'pegel', file: 'pegel.geojson', color: '#000', groupLabel: 'Pegel', pegelStats: true };
        const p = { name: 'Pegel Test', mq_m3s: '1.5', nq_m3s: '0.1', mnq_m3s: '0.5', hq_m3s: '10.0' };

        const popupHtml = await renderPopupHtml(page, p, cfg);
        expect(popupHtml).toContain('📊 NQ');
        expect(popupHtml).toContain('1.5');
        expect(popupHtml).toContain('0.1');
        expect(popupHtml).toContain('Kritisch (Dürre-Trend)');
        expect(popupHtml).toContain('#ef4444');
    });

    test('renders energy efficiency correctly based on ausbaugroesse_ew and id', async ({ page }) => {
        const cfg = { id: 'klaeranlagen', file: 'klaeranlagen.geojson', color: '#000', groupLabel: 'Kläranlage' };
        const p = { name: 'Kläranlage Test', anlagen_nr: '10', ausbaugroesse_ew: 200000 };

        const popupHtml = await renderPopupHtml(page, p, cfg);
        expect(popupHtml).toContain('⚡ Energieeffizienz');
        expect(popupHtml).toContain('Klasse B');
        expect(popupHtml).toContain('#4ade80');
    });

    test('incorporates getZustaendigkeitHtml if defined globally', async ({ page }) => {
        // We set global before rendering
        await page.evaluate(() => {
            window.getZustaendigkeitHtml = () => '<div class="zustaendigkeit-mock">Mocked Zustaendigkeit</div>';
        });
        const cfg = { id: 'test', file: 'test.geojson', color: '#000', groupLabel: 'Test' };
        const p = { name: 'Test' };

        const popupHtml = await renderPopupHtml(page, p, cfg);
        expect(popupHtml).toContain('<div class="zustaendigkeit-mock">Mocked Zustaendigkeit</div>');
    });

    test('renders custom footer template', async ({ page }) => {
        const cfg = {
            id: 'test', file: 'test.geojson', color: '#000', groupLabel: 'Test',
            footerTemplateStr: '(p) => `Custom Footer for ${p.name}`'
        };
        const p = { name: 'Test' };

        const popupHtml = await renderPopupHtml(page, p, cfg);
        expect(popupHtml).toContain('Custom Footer for Test');
    });

    test('renders glossar icons and suffixes', async ({ page }) => {
        const cfg = { id: 'test', file: 'test.geojson', color: '#ff0000', groupLabel: 'Test Group', popupFields: [{ label: 'Wert', field: 'feld', glossar: 'TEST_GLOSSAR', suffix: ' kg' }] };
        const p = { feld: '100' };

        const popupHtml = await renderPopupHtml(page, p, cfg);
        expect(popupHtml).toContain('<span class="glossar-icon" data-glossar="TEST_GLOSSAR">i</span>');
        expect(popupHtml).toContain('Wert');
        expect(popupHtml).toContain(': 100 kg');
    });
});
